# Generated by Django 5.1.15 on 2026-06-30 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon_class', models.CharField(blank=True, help_text='Classe Bootstrap Icons, ex : bi-building', max_length=50, verbose_name="Classe d'icône")),
                ('short_description', models.TextField(help_text='Pour les cartes résumées (1-2 phrases)', verbose_name='Description courte')),
                ('short_description_fr', models.TextField(help_text='Pour les cartes résumées (1-2 phrases)', null=True, verbose_name='Description courte')),
                ('short_description_ar', models.TextField(help_text='Pour les cartes résumées (1-2 phrases)', null=True, verbose_name='Description courte')),
                ('short_description_en', models.TextField(help_text='Pour les cartes résumées (1-2 phrases)', null=True, verbose_name='Description courte')),
                ('long_description', models.TextField(help_text='Description complète affichée sur la page Services', verbose_name='Description détaillée')),
                ('long_description_fr', models.TextField(help_text='Description complète affichée sur la page Services', null=True, verbose_name='Description détaillée')),
                ('long_description_ar', models.TextField(help_text='Description complète affichée sur la page Services', null=True, verbose_name='Description détaillée')),
                ('long_description_en', models.TextField(help_text='Description complète affichée sur la page Services', null=True, verbose_name='Description détaillée')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image')),
                ('image_alt', models.CharField(blank=True, max_length=150, verbose_name='Texte alternatif image')),
                ('image_alt_fr', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image')),
                ('image_alt_ar', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image')),
                ('image_alt_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/gallery/', verbose_name='Image')),
                ('alt_text', models.CharField(max_length=150, verbose_name='Texte alternatif')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Image de service',
                'verbose_name_plural': 'Images de service',
                'ordering': ['ordering'],
            },
        ),
    ]
