# Generated by Django 5.1.15 on 2026-07-03 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, help_text='Courte description affichée sous le titre', max_length=300, verbose_name='Sous-titre')),
                ('subtitle_fr', models.CharField(blank=True, help_text='Courte description affichée sous le titre', max_length=300, null=True, verbose_name='Sous-titre')),
                ('subtitle_ar', models.CharField(blank=True, help_text='Courte description affichée sous le titre', max_length=300, null=True, verbose_name='Sous-titre')),
                ('subtitle_en', models.CharField(blank=True, help_text='Courte description affichée sous le titre', max_length=300, null=True, verbose_name='Sous-titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image 1')),
                ('image1_alt', models.CharField(blank=True, max_length=150, verbose_name='Texte alternatif image 1')),
                ('image1_alt_fr', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 1')),
                ('image1_alt_ar', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 1')),
                ('image1_alt_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image 2')),
                ('image2_alt', models.CharField(blank=True, max_length=150, verbose_name='Texte alternatif image 2')),
                ('image2_alt_fr', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 2')),
                ('image2_alt_ar', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 2')),
                ('image2_alt_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image 3')),
                ('image3_alt', models.CharField(blank=True, max_length=150, verbose_name='Texte alternatif image 3')),
                ('image3_alt_fr', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 3')),
                ('image3_alt_ar', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 3')),
                ('image3_alt_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 3')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['ordering'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Créé le'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='image1_alt',
            field=models.CharField(blank=True, max_length=150, verbose_name='Texte alternatif image 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='image1_alt_ar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='image1_alt_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='image1_alt_fr',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='image2_alt',
            field=models.CharField(blank=True, max_length=150, verbose_name='Texte alternatif image 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='image2_alt_ar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='image2_alt_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='image2_alt_fr',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image 3'),
        ),
        migrations.AddField(
            model_name='service',
            name='image3_alt',
            field=models.CharField(blank=True, max_length=150, verbose_name='Texte alternatif image 3'),
        ),
        migrations.AddField(
            model_name='service',
            name='image3_alt_ar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 3'),
        ),
        migrations.AddField(
            model_name='service',
            name='image3_alt_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 3'),
        ),
        migrations.AddField(
            model_name='service',
            name='image3_alt_fr',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image 3'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Courte description affichée sous le titre', max_length=300, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle_ar',
            field=models.CharField(blank=True, help_text='Courte description affichée sous le titre', max_length=300, null=True, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Courte description affichée sous le titre', max_length=300, null=True, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='service',
            name='subtitle_fr',
            field=models.CharField(blank=True, help_text='Courte description affichée sous le titre', max_length=300, null=True, verbose_name='Sous-titre'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_alt',
            field=models.CharField(blank=True, max_length=150, verbose_name='Texte alternatif image principale'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_alt_ar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image principale'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_alt_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image principale'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_alt_fr',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image principale'),
        ),
    ]
