# Generated by Django 5.1.15 on 2026-06-30 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='Titre du poste')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Titre du poste')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Titre du poste')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('department_fr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Département')),
                ('department_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Département')),
                ('department_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Département')),
                ('location', models.CharField(default='Tanger, Maroc', max_length=100, verbose_name='Lieu')),
                ('location_fr', models.CharField(default='Tanger, Maroc', max_length=100, null=True, verbose_name='Lieu')),
                ('location_ar', models.CharField(default='Tanger, Maroc', max_length=100, null=True, verbose_name='Lieu')),
                ('location_en', models.CharField(default='Tanger, Maroc', max_length=100, null=True, verbose_name='Lieu')),
                ('contract_type', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('Stage', 'Stage'), ('Freelance', 'Freelance')], default='CDI', max_length=20, verbose_name='Type de contrat')),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('description_fr', models.TextField(null=True, verbose_name='Description du poste')),
                ('description_ar', models.TextField(null=True, verbose_name='Description du poste')),
                ('description_en', models.TextField(null=True, verbose_name='Description du poste')),
                ('requirements', models.TextField(help_text='Qualifications et compétences requises', verbose_name='Profil recherché')),
                ('requirements_fr', models.TextField(help_text='Qualifications et compétences requises', null=True, verbose_name='Profil recherché')),
                ('requirements_ar', models.TextField(help_text='Qualifications et compétences requises', null=True, verbose_name='Profil recherché')),
                ('requirements_en', models.TextField(help_text='Qualifications et compétences requises', null=True, verbose_name='Profil recherché')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('posted_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('cv_file', models.FileField(upload_to='applications/cvs/', verbose_name='CV (PDF, DOC, DOCX)')),
                ('cover_message', models.TextField(blank=True, verbose_name='Message de motivation')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Soumis le')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Examiné')),
                ('position', models.ForeignKey(blank=True, help_text='Laisser vide pour candidature spontanée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='recruitment.jobposting', verbose_name='Poste')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
