# Generated by Django 5.1.15 on 2026-06-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+212 660 78 50 38', max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(default='contact@medicenters.ma', max_length=254, verbose_name='Email')),
                ('address', models.TextField(default='Boulevard Mohammed V, Résidence Redouane Chirine 112 N°48, Tanger, Morocco', verbose_name='Adresse')),
                ('address_fr', models.TextField(default='Boulevard Mohammed V, Résidence Redouane Chirine 112 N°48, Tanger, Morocco', null=True, verbose_name='Adresse')),
                ('address_ar', models.TextField(default='Boulevard Mohammed V, Résidence Redouane Chirine 112 N°48, Tanger, Morocco', null=True, verbose_name='Adresse')),
                ('address_en', models.TextField(default='Boulevard Mohammed V, Résidence Redouane Chirine 112 N°48, Tanger, Morocco', null=True, verbose_name='Adresse')),
                ('hours_weekday', models.CharField(default='Lundi–Vendredi 09:00–20:00', max_length=100, verbose_name='Horaires semaine')),
                ('hours_weekday_fr', models.CharField(default='Lundi–Vendredi 09:00–20:00', max_length=100, null=True, verbose_name='Horaires semaine')),
                ('hours_weekday_ar', models.CharField(default='Lundi–Vendredi 09:00–20:00', max_length=100, null=True, verbose_name='Horaires semaine')),
                ('hours_weekday_en', models.CharField(default='Lundi–Vendredi 09:00–20:00', max_length=100, null=True, verbose_name='Horaires semaine')),
                ('hours_saturday', models.CharField(default='Samedi 09:00–15:00', max_length=100, verbose_name='Horaires samedi')),
                ('hours_saturday_fr', models.CharField(default='Samedi 09:00–15:00', max_length=100, null=True, verbose_name='Horaires samedi')),
                ('hours_saturday_ar', models.CharField(default='Samedi 09:00–15:00', max_length=100, null=True, verbose_name='Horaires samedi')),
                ('hours_saturday_en', models.CharField(default='Samedi 09:00–15:00', max_length=100, null=True, verbose_name='Horaires samedi')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/medicenters', verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/medicenters_performance', verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/company/medicenters', verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com/@medicenters', verbose_name='YouTube')),
                ('google_maps_embed_url', models.URLField(blank=True, help_text='URL iframe src pour la carte Google Maps sur la page Contact', verbose_name='URL Google Maps (embed)')),
            ],
            options={
                'verbose_name': 'Informations entreprise',
                'verbose_name_plural': 'Informations entreprise',
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('matterport_embed_url', models.URLField(help_text='URL complète, ex : https://my.matterport.com/show/?m=SPACE_ID', verbose_name='URL Matterport Showcase')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='showrooms/', verbose_name='Image de couverture')),
                ('cover_image_alt', models.CharField(blank=True, max_length=150, verbose_name='Texte alternatif image')),
                ('is_featured', models.BooleanField(default=False, help_text="Mettre en avant sur la page d'accueil", verbose_name="Afficher en page d'accueil")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Showroom virtuel',
                'verbose_name_plural': 'Showrooms virtuels',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('client_name_fr', models.CharField(max_length=100, null=True, verbose_name='Nom du client')),
                ('client_name_ar', models.CharField(max_length=100, null=True, verbose_name='Nom du client')),
                ('client_name_en', models.CharField(max_length=100, null=True, verbose_name='Nom du client')),
                ('client_role', models.CharField(help_text='Ex : Directeur de clinique, Médecin généraliste', max_length=100, verbose_name='Fonction')),
                ('client_role_fr', models.CharField(help_text='Ex : Directeur de clinique, Médecin généraliste', max_length=100, null=True, verbose_name='Fonction')),
                ('client_role_ar', models.CharField(help_text='Ex : Directeur de clinique, Médecin généraliste', max_length=100, null=True, verbose_name='Fonction')),
                ('client_role_en', models.CharField(help_text='Ex : Directeur de clinique, Médecin généraliste', max_length=100, null=True, verbose_name='Fonction')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Entreprise')),
                ('company_fr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entreprise')),
                ('company_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entreprise')),
                ('company_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Entreprise')),
                ('content', models.TextField(verbose_name='Témoignage')),
                ('content_fr', models.TextField(null=True, verbose_name='Témoignage')),
                ('content_ar', models.TextField(null=True, verbose_name='Témoignage')),
                ('content_en', models.TextField(null=True, verbose_name='Témoignage')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('photo_alt', models.CharField(blank=True, max_length=150, verbose_name='Texte alternatif photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['ordering'],
            },
        ),
    ]
