# Generated by Django 5.1.15 on 2026-07-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom',
            name='panorama_image',
            field=models.ImageField(blank=True, help_text="Image équirectangulaire pour la visite virtuelle 360°. Prioritaire sur l'URL Matterport.", null=True, upload_to='showrooms/', verbose_name='Image panoramique 360°'),
        ),
        migrations.AlterField(
            model_name='showroom',
            name='matterport_embed_url',
            field=models.URLField(blank=True, help_text='URL complète, ex : https://my.matterport.com/show/?m=SPACE_ID', verbose_name='URL Matterport Showcase'),
        ),
    ]
