# Generated by Django 5.1.15 on 2026-07-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_showroom_panorama_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Ex : G-XXXXXXX. Laissez vide pour désactiver le suivi.', max_length=50, verbose_name='ID Google Analytics'),
        ),
    ]
