# Generated by Django 5.1.15 on 2026-07-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyinfo_google_analytics_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('logo', models.ImageField(blank=True, help_text='Logo du partenaire (optionnel). Laissez vide pour afficher uniquement le nom.', null=True, upload_to='partners/', verbose_name='Logo')),
                ('website_url', models.URLField(blank=True, verbose_name='Site web')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Référence / Partenaire',
                'verbose_name_plural': 'Références / Partenaires',
                'ordering': ['ordering'],
            },
        ),
    ]
