# Generated by Django 5.1.15 on 2026-07-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='google_search_console_id',
            field=models.CharField(blank=True, help_text='Code de vérification Google Search Console (le code dans le champ content="..."). Laissez vide pour désactiver.', max_length=100, verbose_name='ID Google Search Console'),
        ),
    ]
