# Generated by Django 5.1.15 on 2026-07-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_companyinfo_google_search_console_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre (Optionnel)')),
                ('image', models.ImageField(upload_to='showroom_gallery/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=150, verbose_name='Texte alternatif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordering', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Image Galerie Showroom',
                'verbose_name_plural': 'Images Galerie Showroom',
                'ordering': ['ordering'],
            },
        ),
    ]
