# Generated by Django 5.1.15 on 2026-06-30 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('name_ar', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titre')),
                ('title_fr', models.CharField(max_length=250, null=True, verbose_name='Titre')),
                ('title_ar', models.CharField(max_length=250, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(max_length=250, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=260, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(help_text='Résumé court pour les listes et le SEO', max_length=300, verbose_name='Extrait')),
                ('excerpt_fr', models.TextField(help_text='Résumé court pour les listes et le SEO', max_length=300, null=True, verbose_name='Extrait')),
                ('excerpt_ar', models.TextField(help_text='Résumé court pour les listes et le SEO', max_length=300, null=True, verbose_name='Extrait')),
                ('excerpt_en', models.TextField(help_text='Résumé court pour les listes et le SEO', max_length=300, null=True, verbose_name='Extrait')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('content_fr', models.TextField(null=True, verbose_name='Contenu')),
                ('content_ar', models.TextField(null=True, verbose_name='Contenu')),
                ('content_en', models.TextField(null=True, verbose_name='Contenu')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Image à la une')),
                ('featured_image_alt', models.CharField(blank=True, max_length=150, verbose_name='Texte alternatif image')),
                ('featured_image_alt_fr', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image')),
                ('featured_image_alt_ar', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image')),
                ('featured_image_alt_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Texte alternatif image')),
                ('author', models.CharField(default='MEDICENTERS PERFORMANCE', max_length=100, verbose_name='Auteur')),
                ('meta_description', models.CharField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160, verbose_name='Méta-description SEO')),
                ('meta_description_fr', models.CharField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160, null=True, verbose_name='Méta-description SEO')),
                ('meta_description_ar', models.CharField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160, null=True, verbose_name='Méta-description SEO')),
                ('meta_description_en', models.CharField(blank=True, help_text='Description pour les moteurs de recherche (max 160 caractères)', max_length=160, null=True, verbose_name='Méta-description SEO')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publié')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['-published_date'],
            },
        ),
    ]
