# Generated by Django 5.1.15 on 2026-07-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('contact_person', models.CharField(max_length=150, verbose_name='Personne de contact')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Téléphone')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('company_website', models.URLField(blank=True, verbose_name='Site web')),
                ('activity_sector', models.CharField(blank=True, max_length=200, verbose_name="Secteur d'activité")),
                ('years_in_business', models.CharField(blank=True, max_length=20, verbose_name="Années d'activité")),
                ('num_employees', models.CharField(blank=True, max_length=50, verbose_name="Nombre d'employés")),
                ('products_of_interest', models.TextField(blank=True, help_text='Quels produits ou services vous intéressent ?', verbose_name="Produits/Services d'intérêt")),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Demande de partenariat',
                'verbose_name_plural': 'Demandes de partenariat',
                'ordering': ['-created_at'],
            },
        ),
    ]
