# Generated by Django 5.1.15 on 2026-07-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipinquiry',
            name='partnership_type',
            field=models.CharField(choices=[('revendeur', 'Revendeur / Distributeur'), ('partenaire', 'Partenaire commercial'), ('investisseur', 'Investisseur')], default='partenaire', max_length=20, verbose_name='Type de partenariat souhaité'),
        ),
    ]
