# Generated by Django 5.1.15 on 2026-07-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnership', '0002_partnershipinquiry_partnership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershipinquiry',
            name='partnership_type',
            field=models.CharField(choices=[('revendeur', 'Revendeur / Distributeur'), ('partenaire', 'Partenaire'), ('investisseur', 'Investisseur')], default='partenaire', max_length=20, verbose_name='Type de partenariat souhaité'),
        ),
    ]
